### ISSUE TITLE
Implement Random types

### ISSUE THREAD

**Issue by zoeself** [fedorpashin/statistical-modeling#20]
The puzzle ``-532401028`` originating from #6 has to be resolved:

https://github.com/fedorpashin/statistical-modeling/blob/e48a7c4caba00e6f7961b8a631094c26fc224674/statistical_modeling/random_value.py#L2-L2

"Implement RandomValue".

The puzzle was created by Fedor Pashin at ``2021-08-16 14:38:06 +0300``. 
Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-08-27T17:58:41.130243``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fedorpashin** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@fedorpashin ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by fedorpashin** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@fedorpashin I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-08-29T16:28:34.590484``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@fedorpashin thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
