### ISSUE TITLE
Refactor the code according to the new design

### ISSUE THREAD

**Issue by fedorpashin** [fedorpashin/statistical-modeling#6]
Related to #5

**Comment by zoeself** [comment]
@fedorpashin thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-08-25T14:48:34.368699``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fedorpashin** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@fedorpashin ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by fedorpashin** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@fedorpashin I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-08-26T17:48:34.215700``.

Estimation here is ``240 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@fedorpashin thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
